// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Chimaki_Shake","status":true,"description":"提供上下震動功能","parameters":{}},
{"name":"DTextPicture","status":true,"description":"[ ver.1.15.0 ]產生動態文字圖片","parameters":{"itemIconSwitchId":"0"}},
{"name":"ww_download_saveload","status":true,"description":"保存到本地","parameters":{"版本":"0.1"}}
];
